#!/bin/bash

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash or
#       ksh, you may want to invoke the shell explicitly.
#
#   (2) The IFS (Internal Field Separator) characters in this script are set to any
#       character except the newline char, so word splitting on $PATH is not an issue.
#       See the comments in this script for the rationale.
#
#   Busybox and similar reduced shells will NOT work, because this script
#   requires all of these POSIX shell features:
#     * functions;
#     * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#       «${var#pattern}», «${var%pattern}»;
#     * compound commands having a status, as «if (...) ; then
#       command; fi»;
#     * various quoting mechanisms, as «$()», backticks and «"..."»;
#     * command substitution, as «$(...)» or backticks `` `` ;
#     * 'local' keyword, if supported by the shell implementation;
#       in some edge cases (like function nesting) a few shell implementations do
#       not support local variables;
#     * 'set -o pipefail', which is not POSIX but very useful (the return code
#       reflects the rightmost exit code of the last command to exit with a
#       non-zero status);
#
#   Limitation:
#   - When used with 'sh -c', some versions of the shell will not
#     interpret the ('-*-' command line as a special directive,
#     so the entire script ends up being executed with 'sh' instead of 'sh
#     -x'. This will cause problems if the user cwd is on a filesystem where
#     'sh' is not in the expected PATH.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
    /*)
        app_path=$link
        ;;
    *)
        app_path=$APP_HOME$link
        ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR_NAME=gradle-wrapper.jar
WRAPPER_DIR=$APP_HOME/gradle/wrapper
WRAPPER_JAR=$WRAPPER_DIR/$APP_JAR_NAME
WRAPPER_PROPERTIES=$WRAPPER_DIR/gradle-wrapper.properties

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
CYGWIN*)
    cygwin=true
    ;;
Darwin*)
    darwin=true
    ;;
MSYS* | MINGW*)
    msys=true
    ;;
NONSTOP*)
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
    case $MAX_FD in
    /*)
        MAX_FD_LIMIT=$( ulimit -H -n )
        if [ $MAX_FD_LIMIT != 'unlimited' ]; then
            MAX_FD=$MAX_FD_LIMIT
        fi
        ;;
    esac
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys"; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg; do
        if
            case $arg in
            -*)
                false
                ;;
            *)
                true
                ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        CLASS="$CLASS $arg"
    done
fi

# Parses the output of "gradle --version" to extract the gradle version
parse_gradle_version() {
    awk '/^Gradle [0-9.]+/{ print $2 }'
}

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1; then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with -I {} and a "$@" that reads the args, it splits
# on spaces, tab, and newline.
export -f parse_gradle_version
JAVA_ARGS=$(
    "$JAVACMD" -Xmx32M -Xms32M -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain --class-path "$CLASSPATH" "$@" |
    xargs -I {} find {} -maxdepth 1 -name "gradle-*-all.zip" -o -name "gradle-*-bin.zip"
)

# Escape application args
save() {
    for i; do echo "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/" ; done | tr '\n' ' '
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command, stacking in reverse order:
#   * DEFAULT_JVM_OPTS
#   * GRADLE_OPTS
#   * JAVA_OPTS
#   * GRADLE_SWITCHES
set -- $DEFAULT_JVM_OPTS $GRADLE_OPTS $JAVA_OPTS $GRADLE_SWITCHES -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
